model: "deepseek-chat"
toc_check_page_num: 12
max_page_num_each_node: 10
max_token_num_each_node: 8000
if_add_node_id: "yes"
if_add_node_summary: "no"
if_add_doc_description: "no"
if_add_node_text: "no"